sudo: false
language: python
python:
  - 2.7
  - 3.4
install: 
  - pip install -r requirements.txt --use-mirrors
  - pip install -r dev-requirements.txt --use-mirrors
script:
  - nosetests --with-coverag tests/unit
after_success:
  coveralls --verbose
