# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .company_plan import CompanyPlanParams
from .company_segments import CompanySegmentsParams
from .company_tags import CompanyTagsParams


class CompanyParams(typing_extensions.TypedDict):
    """
    Companies allow you to represent organizations using your product. Each company will have its own description and be associated with contacts. You can fetch, create, update and list companies.
    """

    id: str
    """
    The Intercom defined id representing the company.
    """

    name: str
    """
    The name of the company.
    """

    app_id: str
    """
    The Intercom defined code of the workspace the company is associated to.
    """

    plan: typing_extensions.NotRequired[CompanyPlanParams]
    company_id: str
    """
    The company id you have defined for the company.
    """

    remote_created_at: typing_extensions.NotRequired[int]
    """
    The time the company was created by you.
    """

    created_at: int
    """
    The time the company was added in Intercom.
    """

    updated_at: int
    """
    The last time the company was updated.
    """

    last_request_at: typing_extensions.NotRequired[int]
    """
    The time the company last recorded making a request.
    """

    size: typing_extensions.NotRequired[int]
    """
    The number of employees in the company.
    """

    website: typing_extensions.NotRequired[str]
    """
    The URL for the company website.
    """

    industry: typing_extensions.NotRequired[str]
    """
    The industry that the company operates in.
    """

    monthly_spend: int
    """
    How much revenue the company generates for your business.
    """

    session_count: int
    """
    How many sessions the company has recorded.
    """

    user_count: int
    """
    The number of users in the company.
    """

    custom_attributes: typing_extensions.NotRequired[typing.Dict[str, typing.Optional[typing.Any]]]
    """
    The custom attributes you have set on the company.
    """

    tags: typing_extensions.NotRequired[CompanyTagsParams]
    """
    The list of tags associated with the company
    """

    segments: typing_extensions.NotRequired[CompanySegmentsParams]
    """
    The list of segments associated with the company
    """
