# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

from .news_item import NewsItemParams
from .newsfeed import NewsfeedParams
from .newsfeed_assignment import NewsfeedAssignmentParams

__all__ = ["NewsItemParams", "NewsfeedAssignmentParams", "NewsfeedParams"]
