# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class NewsfeedAssignmentParams(typing_extensions.TypedDict):
    """
    Assigns a news item to a newsfeed.
    """

    newsfeed_id: int
    """
    The unique identifier for the newsfeed which is given by Intercom. Publish dates cannot be in the future, to schedule news items use the dedicated feature in app (see this article).
    """

    published_at: int
    """
    Publish date of the news item on the newsfeed, use this field if you want to set a publish date in the past (e.g. when importing existing news items). On write, this field will be ignored if the news item state is "draft".
    """
