# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..types.news_item_state import NewsItemState
from .newsfeed_assignment import NewsfeedAssignmentParams


class NewsItemParams(typing_extensions.TypedDict):
    """
    A News Item is a content type in Intercom enabling you to announce product updates, company news, promotions, events and more with your customers.
    """

    type: typing.Literal["news-item"]
    """
    The type of object.
    """

    id: str
    """
    The unique identifier for the news item which is given by Intercom.
    """

    workspace_id: str
    """
    The id of the workspace which the news item belongs to.
    """

    title: str
    """
    The title of the news item.
    """

    body: str
    """
    The news item body, which may contain HTML.
    """

    sender_id: int
    """
    The id of the sender of the news item. Must be a teammate on the workspace.
    """

    state: NewsItemState
    """
    News items will not be visible to your users in the assigned newsfeeds until they are set live.
    """

    newsfeed_assignments: typing_extensions.NotRequired[typing.Sequence[NewsfeedAssignmentParams]]
    """
    A list of newsfeed_assignments to assign to the specified newsfeed.
    """

    labels: typing_extensions.NotRequired[typing.Sequence[typing.Optional[str]]]
    """
    Label names displayed to users to categorize the news item.
    """

    cover_image_url: typing_extensions.NotRequired[str]
    """
    URL of the image used as cover. Must have .jpg or .png extension.
    """

    reactions: typing_extensions.NotRequired[typing.Sequence[typing.Optional[str]]]
    """
    Ordered list of emoji reactions to the news item. When empty, reactions are disabled.
    """

    deliver_silently: typing_extensions.NotRequired[bool]
    """
    When set to true, the news item will appear in the messenger newsfeed without showing a notification badge.
    """

    created_at: int
    """
    Timestamp for when the news item was created.
    """

    updated_at: typing_extensions.NotRequired[int]
    """
    Timestamp for when the news item was last updated.
    """
