# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .article_search_highlights_highlighted_summary_item_item import (
    ArticleSearchHighlightsHighlightedSummaryItemItemParams,
)
from .article_search_highlights_highlighted_title_item import ArticleSearchHighlightsHighlightedTitleItemParams


class ArticleSearchHighlightsParams(typing_extensions.TypedDict):
    """
    The highlighted results of an Article search. In the examples provided my search query is always "my query".
    """

    article_id: typing_extensions.NotRequired[str]
    """
    The ID of the corresponding article.
    """

    highlighted_title: typing_extensions.NotRequired[typing.Sequence[ArticleSearchHighlightsHighlightedTitleItemParams]]
    """
    An Article title highlighted.
    """

    highlighted_summary: typing_extensions.NotRequired[
        typing.Sequence[typing.Sequence[ArticleSearchHighlightsHighlightedSummaryItemItemParams]]
    ]
    """
    An Article description and body text highlighted.
    """
