# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.article_search_highlights_highlighted_title_item_type import (
    ArticleSearchHighlightsHighlightedTitleItemType,
)


class ArticleSearchHighlightsHighlightedTitleItemParams(typing_extensions.TypedDict):
    """
    A highlighted article title.
    """

    type: typing_extensions.NotRequired[ArticleSearchHighlightsHighlightedTitleItemType]
    """
    The type of text - `highlight` or `plain`.
    """

    text: typing_extensions.NotRequired[str]
    """
    The text of the title.
    """
