# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class TicketPartUpdatedAttributeDataAttributeParams(typing_extensions.TypedDict):
    """
    Information about the attribute that was updated.
    """

    type: typing.Literal["attribute"]
    """
    The type of the object. Always 'attribute'.
    """

    id: str
    """
    The unique identifier of the attribute.
    """

    label: str
    """
    The human-readable name of the attribute.
    """
