# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ...requests.linked_object_list import LinkedObjectListParams
from ...requests.ticket_custom_attributes import TicketCustomAttributesParams
from ...requests.ticket_parts import TicketPartsParams
from ..types.ticket_category import TicketCategory
from .ticket_contacts import TicketContactsParams
from .ticket_state import TicketStateParams
from .ticket_type import TicketTypeParams


class TicketParams(typing_extensions.TypedDict):
    """
    Tickets are how you track requests from your users.
    """

    type: typing_extensions.NotRequired[typing.Literal["ticket"]]
    """
    Always ticket
    """

    id: typing_extensions.NotRequired[str]
    """
    The unique identifier for the ticket which is given by Intercom.
    """

    ticket_id: typing_extensions.NotRequired[str]
    """
    The ID of the Ticket used in the Intercom Inbox and Messenger. Do not use ticket_id for API queries.
    """

    category: typing_extensions.NotRequired[TicketCategory]
    """
    Category of the Ticket.
    """

    ticket_attributes: typing_extensions.NotRequired[TicketCustomAttributesParams]
    ticket_state: typing_extensions.NotRequired[TicketStateParams]
    ticket_type: typing_extensions.NotRequired[TicketTypeParams]
    contacts: typing_extensions.NotRequired[TicketContactsParams]
    admin_assignee_id: typing_extensions.NotRequired[str]
    """
    The id representing the admin assigned to the ticket.
    """

    team_assignee_id: typing_extensions.NotRequired[str]
    """
    The id representing the team assigned to the ticket.
    """

    created_at: typing_extensions.NotRequired[int]
    """
    The time the ticket was created as a UTC Unix timestamp.
    """

    updated_at: typing_extensions.NotRequired[int]
    """
    The last time the ticket was updated as a UTC Unix timestamp.
    """

    open: typing_extensions.NotRequired[bool]
    """
    Whether or not the ticket is open. If false, the ticket is closed.
    """

    snoozed_until: typing_extensions.NotRequired[int]
    """
    The time the ticket will be snoozed until as a UTC Unix timestamp. If null, the ticket is not currently snoozed.
    """

    linked_objects: typing_extensions.NotRequired[LinkedObjectListParams]
    ticket_parts: typing_extensions.NotRequired[TicketPartsParams]
    is_shared: typing_extensions.NotRequired[bool]
    """
    Whether or not the ticket is shared with the customer.
    """
