# This file was auto-generated by Fern from our API Definition.

import typing

ConversationSlaTargetMissedSlaTargetType = typing.Union[
    typing.Literal["first_reply_time", "next_reply_time", "resolution_time", "time_to_close"], typing.Any
]
