# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel


class ConversationSlaUnpaused(UncheckedBaseModel):
    """
    Contains basic SLA information when unpaused for conversation part type <code>conversation_sla_unpaused</code>.
    """

    sla_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the SLA being unpaused
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
