# This file was auto-generated by Fern from our API Definition.

import typing

ConversationSlaTargetMissedCurrentSlaStatus = typing.Union[
    typing.Literal["hit", "missed", "active", "paused", "canceled"], typing.Any
]
