# This file was auto-generated by Fern from our API Definition.

import typing

from .customer_request_email import CustomerRequestEmail
from .customer_request_intercom_user_id import CustomerRequestIntercomUserId
from .customer_request_user_id import CustomerRequestUserId

CustomerRequest = typing.Union[CustomerRequestIntercomUserId, CustomerRequestUserId, CustomerRequestEmail]
