# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from ..data_attributes.types.data_attribute import DataAttribute


class DataAttributeList(UncheckedBaseModel):
    """
    A list of all data attributes belonging to a workspace for contacts, companies or conversations.
    """

    type: typing.Optional[typing.Literal["list"]] = pydantic.Field(default=None)
    """
    The type of the object
    """

    data: typing.Optional[typing.List[DataAttribute]] = pydantic.Field(default=None)
    """
    A list of data attributes
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
