# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.admin_reply_ticket_request import AdminReplyTicketRequest
from ...types.contact_reply_ticket_request import ContactReplyTicketRequest

TicketsReplyRequestBody = typing.Union[ContactReplyTicketRequest, AdminReplyTicketRequest]
