# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel


class UpdateTicketRequestAssignment(UncheckedBaseModel):
    admin_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID of the admin performing the action.
    """

    assignee_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID of the admin or team to which the ticket is assigned. Set this 0 to unassign it.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
