# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from ...types.pages_link import PagesLink
from .content_import_source import ContentImportSource


class ContentImportSourcesList(UncheckedBaseModel):
    """
    This will return a list of the content import sources for the App.
    """

    type: typing.Optional[typing.Literal["list"]] = pydantic.Field(default=None)
    """
    The type of the object - `list`.
    """

    pages: typing.Optional[PagesLink] = None
    total_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    A count of the total number of content import sources.
    """

    data: typing.Optional[typing.List[ContentImportSource]] = pydantic.Field(default=None)
    """
    An array of Content Import Source objects
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
