# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .contact_reference import ContactReference


class ConversationContacts(UncheckedBaseModel):
    """
    The list of contacts (users or leads) involved in this conversation. This will only contain one customer unless more were added via the group conversation feature.
    """

    type: typing.Literal["contact.list"] = "contact.list"
    contacts: typing.List[ContactReference] = pydantic.Field()
    """
    The list of contacts (users or leads) involved in this conversation. This will only contain one customer unless more were added via the group conversation feature.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
