# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .custom_action_finished_action import CustomActionFinishedAction


class CustomActionFinished(UncheckedBaseModel):
    """
    Contains details about final status of the completed action for conversation part type <code>custom_action_finished</code>.
    """

    action: typing.Optional[CustomActionFinishedAction] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
