# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from ..data_events.types.data_event import DataEvent
from .data_event_list_pages import DataEventListPages


class DataEventList(UncheckedBaseModel):
    """
    This will return a list of data events for the App.
    """

    type: typing.Optional[typing.Literal["event.list"]] = pydantic.Field(default=None)
    """
    The type of the object
    """

    events: typing.Optional[typing.List[DataEvent]] = pydantic.Field(default=None)
    """
    A list of data events
    """

    pages: typing.Optional[DataEventListPages] = pydantic.Field(default=None)
    """
    Pagination
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
