# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .list_item import ListItem


class ListItemWithImage(ListItem):
    image: str = pydantic.Field()
    """
    An image that will be displayed to the left of the item.
    """

    image_width: int = pydantic.Field()
    """
    The exact width of the image in pixels.
    """

    image_height: int = pydantic.Field()
    """
    The exact height of the image in pixels.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
