# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from ..news.types.newsfeed import Newsfeed
from .cursor_pages import CursorPages


class PaginatedNewsfeedResponse(UncheckedBaseModel):
    """
    Paginated Newsfeed Response
    """

    type: typing.Literal["list"] = pydantic.Field(default="list")
    """
    The type of object
    """

    pages: typing.Optional[CursorPages] = None
    total_count: int = pydantic.Field()
    """
    A count of the total number of Newsfeeds.
    """

    data: typing.List[Newsfeed] = pydantic.Field()
    """
    An array of Newsfeeds
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
