# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class PartAttachment(UncheckedBaseModel):
    """
    The file attached to a part
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    The type of attachment
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the attachment
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    The URL of the attachment
    """

    content_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    The content type of the attachment
    """

    filesize: typing.Optional[int] = pydantic.Field(default=None)
    """
    The size of the attachment
    """

    width: typing.Optional[int] = pydantic.Field(default=None)
    """
    The width of the attachment
    """

    height: typing.Optional[int] = pydantic.Field(default=None)
    """
    The height of the attachment
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
