# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class TeamPriorityLevel(UncheckedBaseModel):
    """
    Admin priority levels for teams
    """

    primary_team_ids: typing.Optional[typing.List[int]] = pydantic.Field(default=None)
    """
    The primary team ids for the team
    """

    secondary_team_ids: typing.Optional[typing.List[int]] = pydantic.Field(default=None)
    """
    The secondary team ids for the team
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
