# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from ..tickets.types.ticket_part import TicketPart


class TicketParts(UncheckedBaseModel):
    """
    A list of Ticket Part objects for each note and event in the ticket. There is a limit of 500 parts.
    """

    type: typing.Literal["ticket_part.list"] = pydantic.Field(default="ticket_part.list")
    """
    
    """

    ticket_parts: typing.List[TicketPart] = pydantic.Field()
    """
    A list of Ticket Part objects for each ticket. There is a limit of 500 parts.
    """

    total_count: int = pydantic.Field()
    """
    
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
