# This file was auto-generated by Fern from our API Definition.

import typing

TicketTypeAttributeDataType = typing.Union[
    typing.Literal["string", "list", "integer", "decimal", "boolean", "datetime", "files"], typing.Any
]
