# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .help_center import HelpCenter


class HelpCenterList(UncheckedBaseModel):
    """
    A list of Help Centers belonging to the App
    """

    type: typing.Literal["list"] = pydantic.Field(default="list")
    """
    The type of the object - `list`.
    """

    data: typing.List[HelpCenter] = pydantic.Field()
    """
    An array of Help Center objects
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
