# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .article_search_highlights_highlighted_title_item_type import ArticleSearchHighlightsHighlightedTitleItemType


class ArticleSearchHighlightsHighlightedTitleItem(UncheckedBaseModel):
    """
    A highlighted article title.
    """

    type: typing.Optional[ArticleSearchHighlightsHighlightedTitleItemType] = pydantic.Field(default=None)
    """
    The type of text - `highlight` or `plain`.
    """

    text: typing.Optional[str] = pydantic.Field(default=None)
    """
    The text of the title.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
