# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.unchecked_base_model import UncheckedBaseModel
from ...notes.types.company_note import CompanyNote


class CompanyNotes(UncheckedBaseModel):
    """
    The list of notes associated with the company
    """

    type: typing.Optional[typing.Literal["note.list"]] = pydantic.Field(default=None)
    """
    The type of the object
    """

    notes: typing.Optional[typing.List[CompanyNote]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
