# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

from .types import (
    AttachContactToConversationRequestCustomer,
    AttachContactToConversationRequestCustomerCustomer,
    AttachContactToConversationRequestCustomerIntercomUserId,
    AttachContactToConversationRequestCustomerUserId,
    Conversation,
    ConversationPriority,
    ConversationState,
    ConversationsManageRequestBody,
    ConversationsManageRequestBody_Assignment,
    ConversationsManageRequestBody_Close,
    ConversationsManageRequestBody_Open,
    ConversationsManageRequestBody_Snoozed,
    CreateConversationRequestFrom,
    CreateConversationRequestFromType,
)

__all__ = [
    "AttachContactToConversationRequestCustomer",
    "AttachContactToConversationRequestCustomerCustomer",
    "AttachContactToConversationRequestCustomerIntercomUserId",
    "AttachContactToConversationRequestCustomerUserId",
    "Conversation",
    "ConversationPriority",
    "ConversationState",
    "ConversationsManageRequestBody",
    "ConversationsManageRequestBody_Assignment",
    "ConversationsManageRequestBody_Close",
    "ConversationsManageRequestBody_Open",
    "ConversationsManageRequestBody_Snoozed",
    "CreateConversationRequestFrom",
    "CreateConversationRequestFromType",
]
