# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .help_center import HelpCenterParams


class HelpCenterListParams(typing_extensions.TypedDict):
    """
    A list of Help Centers belonging to the App
    """

    type: typing_extensions.NotRequired[typing.Literal["list"]]
    """
    The type of the object - `list`.
    """

    data: typing_extensions.NotRequired[typing.Sequence[HelpCenterParams]]
    """
    An array of Help Center objects
    """
