# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class CloseConversationRequestParams(typing_extensions.TypedDict):
    """
    Payload of the request to close a conversation
    """

    type: typing.Literal["admin"]
    admin_id: str
    """
    The id of the admin who is performing the action.
    """

    body: typing_extensions.NotRequired[str]
    """
    Optionally you can leave a message in the conversation to provide additional context to the user and other teammates.
    """
