# This file was auto-generated by Fern from our API Definition.

import typing

from .contact_reply_ticket_email_request import ContactReplyTicketEmailRequestParams
from .contact_reply_ticket_intercom_user_id_request import ContactReplyTicketIntercomUserIdRequestParams
from .contact_reply_ticket_user_id_request import ContactReplyTicketUserIdRequestParams

ContactReplyTicketRequestParams = typing.Union[
    ContactReplyTicketIntercomUserIdRequestParams,
    ContactReplyTicketUserIdRequestParams,
    ContactReplyTicketEmailRequestParams,
]
