# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .conversation_part_metadata_quick_reply_options_item import ConversationPartMetadataQuickReplyOptionsItemParams


class ConversationPartMetadataParams(typing_extensions.TypedDict):
    """
    Metadata for a conversation part
    """

    quick_reply_options: typing_extensions.NotRequired[
        typing.Sequence[ConversationPartMetadataQuickReplyOptionsItemParams]
    ]
    """
    The quick reply options sent by the Admin or bot, presented in this conversation part.
    """

    quick_reply_uuid: typing_extensions.NotRequired[str]
    """
    The unique identifier for the quick reply option that was clicked by the end user.
    """
