# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..tags.requests.tag_basic import TagBasicParams
from ..types.conversation_part_state import ConversationPartState
from .conversation_part_author import ConversationPartAuthorParams
from .conversation_part_metadata import ConversationPartMetadataParams
from .email_message_metadata import EmailMessageMetadataParams
from .event_details import EventDetailsParams
from .part_attachment import PartAttachmentParams
from .reference import ReferenceParams


class ConversationPartParams(typing_extensions.TypedDict):
    """
    A Conversation Part represents a message in the conversation.
    """

    type: typing_extensions.NotRequired[str]
    """
    Always conversation_part
    """

    id: typing_extensions.NotRequired[str]
    """
    The id representing the conversation part.
    """

    part_type: typing_extensions.NotRequired[str]
    """
    The type of conversation part.
    """

    body: typing_extensions.NotRequired[str]
    """
    The message body, which may contain HTML. For Twitter, this will show a generic message regarding why the body is obscured.
    """

    created_at: typing_extensions.NotRequired[int]
    """
    The time the conversation part was created.
    """

    updated_at: typing_extensions.NotRequired[int]
    """
    The last time the conversation part was updated.
    """

    notified_at: typing_extensions.NotRequired[int]
    """
    The time the user was notified with the conversation part.
    """

    assigned_to: typing_extensions.NotRequired[ReferenceParams]
    """
    The id of the admin that was assigned the conversation by this conversation_part (null if there has been no change in assignment.)
    """

    author: typing_extensions.NotRequired[ConversationPartAuthorParams]
    attachments: typing_extensions.NotRequired[typing.Sequence[PartAttachmentParams]]
    """
    A list of attachments for the part.
    """

    external_id: typing_extensions.NotRequired[str]
    """
    The external id of the conversation part
    """

    redacted: typing_extensions.NotRequired[bool]
    """
    Whether or not the conversation part has been redacted.
    """

    email_message_metadata: typing_extensions.NotRequired[EmailMessageMetadataParams]
    metadata: typing_extensions.NotRequired[ConversationPartMetadataParams]
    state: typing_extensions.NotRequired[ConversationPartState]
    """
    Indicates the current state of conversation when the conversation part was created.
    """

    tags: typing_extensions.NotRequired[typing.Sequence[TagBasicParams]]
    """
    A list of tags objects associated with the conversation part.
    """

    event_details: typing_extensions.NotRequired[EventDetailsParams]
    app_package_code: typing_extensions.NotRequired[str]
    """
    The app package code if this part was created via API. null if the part was not created via API.
    """
