# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class CustomObjectInstanceDeletedParams(typing_extensions.TypedDict):
    """
    deleted custom object instance object
    """

    object: typing_extensions.NotRequired[str]
    """
    The unique identifier of the Custom Object type that defines the structure of the Custom Object instance.
    """

    id: typing_extensions.NotRequired[str]
    """
    The Intercom defined id representing the Custom Object instance.
    """

    deleted: typing_extensions.NotRequired[bool]
    """
    Whether the Custom Object instance is deleted or not.
    """
