# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class CustomActionStartedActionParams(typing_extensions.TypedDict):
    name: typing_extensions.NotRequired[str]
    """
    Name of the action
    """
