# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class DataEventSummaryItemParams(typing_extensions.TypedDict):
    """
    This will return a summary of a data event for the App.
    """

    name: typing_extensions.NotRequired[str]
    """
    The name of the event
    """

    first: typing_extensions.NotRequired[str]
    """
    The first time the event was sent
    """

    last: typing_extensions.NotRequired[str]
    """
    The last time the event was sent
    """

    count: typing_extensions.NotRequired[int]
    """
    The number of times the event was sent
    """

    description: typing_extensions.NotRequired[str]
    """
    The description of the event
    """
