# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.recipient_type import RecipientType


class RecipientParams(typing_extensions.TypedDict):
    """
    A recipient of a message
    """

    type: RecipientType
    """
    The role associated to the contact - `user` or `lead`.
    """

    id: str
    """
    The identifier for the contact which is given by Intercom.
    """
