# This file was auto-generated by Fern from our API Definition.

import typing

from .single_filter_search_request_value_item import SingleFilterSearchRequestValueItemParams

SingleFilterSearchRequestValueParams = typing.Union[str, int, typing.Sequence[SingleFilterSearchRequestValueItemParams]]
