# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .tag_multiple_users_request_users_item import TagMultipleUsersRequestUsersItemParams


class TagMultipleUsersRequestParams(typing_extensions.TypedDict):
    """
    You can tag a list of users.
    """

    name: str
    """
    The name of the tag, which will be created if not found.
    """

    users: typing.Sequence[TagMultipleUsersRequestUsersItemParams]
