# This file was auto-generated by Fern from our API Definition.

import typing

TicketRequestCustomAttributesValueParams = typing.Union[
    typing.Optional[str], float, bool, typing.Sequence[typing.Optional[typing.Any]]
]
