# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class TicketTypeAttributeParams(typing_extensions.TypedDict):
    """
    Ticket type attribute, used to define each data field to be captured in a ticket.
    """

    type: typing_extensions.NotRequired[str]
    """
    String representing the object's type. Always has the value `ticket_type_attribute`.
    """

    id: typing_extensions.NotRequired[str]
    """
    The id representing the ticket type attribute.
    """

    workspace_id: typing_extensions.NotRequired[str]
    """
    The id of the workspace that the ticket type attribute belongs to.
    """

    name: typing_extensions.NotRequired[str]
    """
    The name of the ticket type attribute
    """

    description: typing_extensions.NotRequired[str]
    """
    The description of the ticket type attribute
    """

    data_type: typing_extensions.NotRequired[str]
    """
    The type of the data attribute (allowed values: "string list integer decimal boolean datetime files")
    """

    input_options: typing_extensions.NotRequired[typing.Dict[str, typing.Optional[typing.Any]]]
    """
    Input options for the attribute
    """

    order: typing_extensions.NotRequired[int]
    """
    The order of the attribute against other attributes
    """

    required_to_create: typing_extensions.NotRequired[bool]
    """
    Whether the attribute is required or not for teammates.
    """

    required_to_create_for_contacts: typing_extensions.NotRequired[bool]
    """
    Whether the attribute is required or not for contacts.
    """

    visible_on_create: typing_extensions.NotRequired[bool]
    """
    Whether the attribute is visible or not to teammates.
    """

    visible_to_contacts: typing_extensions.NotRequired[bool]
    """
    Whether the attribute is visible or not to contacts.
    """

    default: typing_extensions.NotRequired[bool]
    """
    Whether the attribute is built in or not.
    """

    ticket_type_id: typing_extensions.NotRequired[int]
    """
    The id of the ticket type that the attribute belongs to.
    """

    archived: typing_extensions.NotRequired[bool]
    """
    Whether the ticket type attribute is archived or not.
    """

    created_at: typing_extensions.NotRequired[int]
    """
    The date and time the ticket type attribute was created.
    """

    updated_at: typing_extensions.NotRequired[int]
    """
    The date and time the ticket type attribute was last updated.
    """
