# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class UntagCompanyRequestCompaniesItemParams(typing_extensions.TypedDict):
    id: typing_extensions.NotRequired[str]
    """
    The Intercom defined id representing the company.
    """

    company_id: typing_extensions.NotRequired[str]
    """
    The company id you have defined for the company.
    """

    untag: typing_extensions.NotRequired[bool]
    """
    Always set to true
    """
