# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..types.article_content_state import ArticleContentState


class ArticleContentParams(typing_extensions.TypedDict):
    """
    The Content of an Article.
    """

    type: typing.Literal["article_content"]
    """
    The type of object - `article_content` .
    """

    title: str
    """
    The title of the article.
    """

    description: str
    """
    The description of the article.
    """

    body: str
    """
    The body of the article.
    """

    author_id: int
    """
    The ID of the author of the article.
    """

    state: ArticleContentState
    """
    Whether the article is `published` or is a `draft` .
    """

    created_at: typing_extensions.NotRequired[int]
    """
    The time when the article was created (seconds).
    """

    updated_at: typing_extensions.NotRequired[int]
    """
    The time when the article was last updated (seconds).
    """

    url: typing_extensions.NotRequired[str]
    """
    The URL of the article.
    """
