# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..types.checkbox_component_save_state import CheckboxComponentSaveState
from .checkbox_option import CheckboxOptionParams


class CheckboxComponentParams(typing_extensions.TypedDict):
    """
    A checkbox component is used to capture multiple choices from as many options as you want to provide. You can submit the options by:

    - Using a ButtonComponent (which will submit all interactive components in the canvas)

    When a submit action takes place, the results are given in a hash with the `id` from the checkbox component used as the key and an array containing the `id` of each chosen option as the value.
    """

    id: str
    """
    A unique identifier for the component.
    """

    option: typing.Sequence[CheckboxOptionParams]
    """
    The list of options. Minimum of 1.
    """

    label: str
    """
    The text shown above the options.
    """

    value: typing_extensions.NotRequired[typing.Sequence[str]]
    """
    The option's that are selected by default.
    """

    save_state: typing_extensions.NotRequired[CheckboxComponentSaveState]
    """
    Styles the input. Default is `unsaved`. Prevent action with `saved`.
    """

    disabled: typing_extensions.NotRequired[bool]
    """
    Styles all options and prevents the action. Default is false. Will be overridden if save_state is saved.
    """
