# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..segments.requests.segment import SegmentParams


class CompanyAttachedSegmentsParams(typing_extensions.TypedDict):
    """
    A list of Segment Objects
    """

    type: typing.Literal["list"]
    """
    The type of object - `list`
    """

    data: typing.Sequence[SegmentParams]
    """
    An array containing Segment Objects
    """
