# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..admins.requests.admin import AdminParams
from .canvas_object import CanvasObjectParams
from .context import ContextParams


class ConfigureRequestComponentIdParams(typing_extensions.TypedDict):
    workspace_id: str
    """
    The workspace ID of the teammate. Attribute is app_id for V1.2 and below.
    """

    workspace_region: str
    """
    The Intercom hosted region that this app is located in.
    """

    component_id: str
    """
    The id of the component clicked by the teammate to trigger the request.
    """

    admin: AdminParams
    """
    The Intercom teammate configuring the app.
    """

    context: ContextParams
    """
    The context of where the app is added, where the user last visited, and information on the Messenger settings.
    """

    current_canvas: CanvasObjectParams
    """
    The current canvas the teammate can see.
    """

    input_values: typing.Dict[str, typing.Optional[typing.Any]]
    """
    A list of key/value pairs of data, inputted by the teammate on the current canvas.
    """
