# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .addressable_list import AddressableListParams


class ContactNotesParams(typing_extensions.TypedDict):
    """
    An object containing notes meta data about the notes that a contact has. Up to 10 will be displayed here. Use the url to get more.
    """

    data: typing.Sequence[AddressableListParams]
    """
    This object represents the notes attached to a contact.
    """

    url: str
    """
    Url to get more company resources for this contact
    """

    total_count: int
    """
    Int representing the total number of companyies attached to this contact
    """

    has_more: bool
    """
    Whether there's more Addressable Objects to be viewed. If true, use the url to view all
    """
