# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class ContactDeletedParams(typing_extensions.TypedDict):
    """
    deleted contact object
    """

    type: typing.Literal["contact"]
    """
    always contact
    """

    id: str
    """
    The unique identifier for the contact which is given by Intercom.
    """

    external_id: typing_extensions.NotRequired[str]
    """
    The unique identifier for the contact which is provided by the Client.
    """

    deleted: bool
    """
    Whether the contact is deleted or not.
    """
