# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .social_profile import SocialProfileParams


class ContactSocialProfilesParams(typing_extensions.TypedDict):
    """
    An object containing social profiles that a contact has.
    """

    data: typing.Sequence[SocialProfileParams]
    """
    A list of social profiles objects associated with the contact.
    """
