# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class DataTableItemParams(typing_extensions.TypedDict):
    """
    A field-value pair component for use in a data table.
    """

    type: typing.Literal["field-value"]
    """
    The type of component you are rendering.
    """

    field: str
    """
    The text of the key in your key-value pair.
    """

    value: str
    """
    The text of the value in your key-value pair.
    """
