# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..data_attributes.requests.data_attribute import DataAttributeParams


class DataAttributeListParams(typing_extensions.TypedDict):
    """
    A list of all data attributes belonging to a workspace for contacts, companies or conversations.
    """

    type: typing.Literal["list"]
    """
    The type of the object
    """

    data: typing.Sequence[DataAttributeParams]
    """
    A list of data attributes
    """
