# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..types.dropdown_component_save_state import DropdownComponentSaveState
from .dropdown_option import DropdownOptionParams


class DropdownComponentParams(typing_extensions.TypedDict):
    """
    A dropdown component is used to capture a choice from the options that you provide.

    When submitted, the dropdown choices are returned in a hash with the id from the dropdown component used as the key and the id from the chosen option as the value.
    """

    id: str
    """
    A unique identifier for the component.
    """

    options: typing.Sequence[DropdownOptionParams]
    """
    The list of options. Can provide 2 to 10.
    """

    label: typing_extensions.NotRequired[str]
    """
    The text shown above the dropdown.
    """

    value: typing_extensions.NotRequired[str]
    """
    The option that is selected by default.
    """

    save_state: typing_extensions.NotRequired[DropdownComponentSaveState]
    """
    Styles all options and prevents the action. Default is `unsaved`. Will be overridden if `save_state` is `saved`.
    """

    disabled: typing_extensions.NotRequired[bool]
    """
    Styles all options and prevents the action. Default is false. Will be overridden if save_state is saved.
    """
