# This file was auto-generated by Fern from our API Definition.

from .list_item import ListItemParams


class ListItemWithImageParams(ListItemParams):
    image: str
    """
    An image that will be displayed to the left of the item.
    """

    image_width: int
    """
    The exact width of the image in pixels.
    """

    image_height: int
    """
    The exact height of the image in pixels.
    """
