# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class OpenConversationRequestParams(typing_extensions.TypedDict):
    """
    Payload of the request to open a conversation
    """

    admin_id: str
    """
    The id of the admin who is performing the action.
    """
