# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class PhoneSwitchParams(typing_extensions.TypedDict):
    """
    Phone Switch Response
    """

    type: typing.Literal["phone_call_redirect"]
    """
    
    """

    phone: str
    """
    Phone number in E.164 format, that has received the SMS to continue the conversation in the Messenger.
    """
