# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class TranslationParams(typing_extensions.TypedDict):
    """
    A translation object contains the localised details of a subscription type.
    """

    name: str
    """
    The localised name of the subscription type.
    """

    description: str
    """
    The localised description of the subscription type.
    """

    locale: str
    """
    The two character identifier for the language of the translation object.
    """
