# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..companies.requests.company import CompanyParams


class VisitorCompaniesParams(typing_extensions.TypedDict):
    type: typing_extensions.NotRequired[typing.Literal["company.list"]]
    """
    The type of the object
    """

    companies: typing_extensions.NotRequired[typing.Sequence[CompanyParams]]
