# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .visitor_tags_tags_item import VisitorTagsTagsItemParams


class VisitorTagsParams(typing_extensions.TypedDict):
    type: typing_extensions.NotRequired[typing.Literal["tag.list"]]
    """
    The type of the object
    """

    tags: typing_extensions.NotRequired[typing.Sequence[VisitorTagsTagsItemParams]]
