# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class DataEventParams(typing_extensions.TypedDict):
    """
    Data events are used to notify Intercom of changes to your data.
    """

    type: typing_extensions.NotRequired[typing.Literal["event"]]
    """
    The type of the object
    """

    event_name: str
    """
    The name of the event that occurred. This is presented to your App's admins when filtering and creating segments - a good event name is typically a past tense 'verb-noun' combination, to improve readability, for example `updated-plan`.
    """

    created_at: int
    """
    The time the event occurred as a UTC Unix timestamp
    """

    user_id: typing_extensions.NotRequired[str]
    """
    Your identifier for the user.
    """

    id: typing_extensions.NotRequired[str]
    """
    Your identifier for a lead or a user.
    """

    intercom_user_id: typing_extensions.NotRequired[str]
    """
    The Intercom identifier for the user.
    """

    email: typing_extensions.NotRequired[str]
    """
    An email address for your user. An email should only be used where your application uses email to uniquely identify users.
    """

    metadata: typing_extensions.NotRequired[typing.Dict[str, str]]
    """
    Optional metadata about the event.
    """
